# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:11
from __future__ import unicode_literals

from django.db import migrations
import slothauth.utils


class Migration(migrations.Migration):

    dependencies = [
        ('test_mocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=slothauth.utils.CiEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
