# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 13:58
from __future__ import unicode_literals

from django.db import migrations
import slothauth.utils


class Migration(migrations.Migration):

    dependencies = [
        ('test_mocks', '0003_account_can_impersonate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='one_time_authentication_key',
            field=slothauth.utils.RandomField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='password_reset_key',
            field=slothauth.utils.RandomField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='passwordless_key',
            field=slothauth.utils.RandomField(blank=True, max_length=32),
        ),
    ]
